name: Markdown Link Check with errors

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Once a week: "At 00:00 on Sunday."

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Markdown Link Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github co  ntext for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - uses: actions/checkout@v3
    - name: Markdown link check with errors
      continue-on-error: true
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        config-file: .github/markdown-link-check-config.json
        folder-path: .github/workflows/markdown-link-check-files/with-errors/
