name: Markdown Link Check log parser

on:
  workflow_run:
    workflows: [
      "Markdown Link Check with errors",
      "Markdown Link Check without errors",
    ]
    types:
    - completed

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Markdown Link Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github co ntext for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - uses: actions/checkout@v3
    - name: Run markdown link check log parser 1
      id: mlc-log-parser-1
      uses: ./
      with:
        auth-token:  '${{ secrets.GITHUB_TOKEN }}'
        repo: '${{ github.repository }}'
        run-id: '${{ github.event.workflow_run.id }}'
        job-name: 'Run Markdown Link Check'
        step-name: 'Markdown Link Check'
        only-errors: 'true'
        output: 'step, json, md'
        json-filepath: './mlc-json-result-1.json'
        markdown-filepath: './mlc-md-result-1.md'
    - name: Dump outputs from previous step
      shell: pwsh
      run: |
        $result = '${{ steps.mlc-log-parser-1.outputs.mlc-result }}' | ConvertFrom-Json
        Write-Output "Total files checked: $($result.TotalFilesChecked)"
        Write-Output "Total links chedked: $($result.TotalLinksChecked)"
        Write-Output "Has erros: $($result.HasErrors)"
        $resultAsJsonIndented = ConvertTo-Json -Depth 4 $result 
        Write-Output $resultAsJsonIndented # outputs the markdown link check result as an indented JSON string
    - name: Output json and md file contents
      shell: pwsh
      run: |
        cat ${{ github.workspace }}/mlc-json-result-1.json
        cat ${{ github.workspace }}/mlc-md-result-1.md
    - uses: actions/checkout@v3
    - name: Run markdown link check log parser 2
      id: mlc-log-parser-2
      uses: ./
      with:
        auth-token:  '${{ secrets.GITHUB_TOKEN }}'
        repo: '${{ github.repository }}'
        run-id: '${{ github.event.workflow_run.id }}'
        job-name: 'Run Markdown Link Check'
        step-name: 'Markdown Link Check'
        only-errors: 'false'
        output: 'step, json, md'
        json-filepath: './mlc-json-result-2.json'
        markdown-filepath: './mlc-md-result-2.md'
    - name: Dump outputs from previous step
      shell: pwsh
      run: |
        $result = '${{ steps.mlc-log-parser-2.outputs.mlc-result }}' | ConvertFrom-Json
        Write-Output "Total files checked: $($result.TotalFilesChecked)"
        Write-Output "Total links chedked: $($result.TotalLinksChecked)"
        Write-Output "Has erros: $($result.HasErrors)"
        $resultAsJsonIndented = ConvertTo-Json -Depth 4 $result 
        Write-Output $resultAsJsonIndented # outputs the markdown link check result as an indented JSON string
    - name: Output json and md file contents
      shell: pwsh
      run: |
        cat ${{ github.workspace }}/mlc-json-result-2.json
        cat ${{ github.workspace }}/mlc-md-result-2.md