name: Markdown Link Check log parser

on:
  workflow_run:
    workflows: [
      "Markdown Link Check with errors",
      "Markdown Link Check without errors",
    ]
    types:
    - completed

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Markdown Link Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Dump github co ntext for debug purposes
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: $env:GITHUB_CONTEXT
    - uses: actions/checkout@v3
    - name: Run markdown link check log parser
      id: mlc-log-parser
      uses: ./
      with:
        auth-token:  ${{ secrets.GITHUB_TOKEN }}
        repo: '${{ github.repository }}'
        run-id: '${{ github.event.workflow_run.id }}'
        job-name: 'Markdown link check'
        step-name: 'Markdown link check'
    - name: Dump outputs from previous step
      shell: pwsh
      run: |
        $result = '${{ steps.mlc-log-parser.outputs.mlc-result }}' | ConvertFrom-Json
        Write-Output "Total files checked: $($result.TotalFilesChecked)"
        Write-Output "Total links chedked: $($result.TotalLinksChecked)"
        Write-Output "Has erros: $($result.HasErrors)"
        $resultAsJsonIndented = ConvertTo-Json $result
        Write-Output $resultAsJsonIndented # outputs the markdown link check result as an indented JSON string